# Generated by Django 3.0.4 on 2020-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200503_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='drives',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drives',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
