# Generated by Django 3.0.6 on 2020-05-05 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200504_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='contributers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_drives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
