# Generated by Django 3.0.6 on 2020-05-05 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200505_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drives',
            name='contributers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, default=None, null=True, size=None), null=True, size=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_drives',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, default=None, null=True, size=None), null=True, size=50),
        ),
    ]
