# Generated by Django 3.0.6 on 2020-05-14 05:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200505_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_drives',
        ),
        migrations.AddField(
            model_name='profile',
            name='mydrives',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='drives',
            name='contributers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
