# Generated by Django 3.0.6 on 2020-05-14 06:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200514_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='contributers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mydrives',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
