# Generated by Django 3.0.6 on 2020-05-14 06:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200514_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='contributers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
    ]
