# Generated by Django 3.0.6 on 2020-05-14 06:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200514_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drives',
            name='mydrives',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mydrives',
        ),
        migrations.AddField(
            model_name='drives',
            name='contributers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, default=None, null=True, size=None), null=True, size=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_drives',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, default=None, null=True, size=None), null=True, size=50),
        ),
    ]
