# Generated by Django 3.0.4 on 2020-04-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('userage', models.IntegerField()),
                ('usergender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('usercity', models.CharField(max_length=50)),
                ('loginpsw', models.CharField(max_length=50)),
            ],
        ),
    ]
