# Generated by Django 3.0.3 on 2020-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allpastdrives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
